const express = require("express")
const app = express()
const bodyParser = require("body-parser")
const session = require("express-session")
const sessionConfig = require("./config/session/sessionConfig")
app.use(bodyParser.urlencoded())
app.use(session(sessionConfig.sessionConfig))
const router = require("./src/router/router")(app)
app.use("/", router)
app.set("views", "./src/views")
app.set("view engine", "ejs")
app.listen(3000, () => { console.log("3000 port server") })